In [70]:

import re
import os
import json
import uuid
import json
import time
import spacy
import numpy as np
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from typing import Dict, Any, Optional


os.getcwd()

'c:\\Users\\maina\\Documents\\kdd-project'

# Loading the job dataset and preprocessing

In [71]:
# Columns we want to keep are: job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips
# We will have zip_code and fips as strings instead of integers because they can have leading zeros, job_id and company_id as strings
# and we dont want to lose that information. Also, we have everything to lowercase to avoid any issues with case sensitivity when we do our analysis later on.

columns_to_keep = ['job_id', 'company_name', 'title', 'description', 'location', 'company_id', 'views', 'skills_desc', 'work_type', 'zip_code', 'fips']

jobs = pd.read_csv('data/postings.csv',
                   usecols=columns_to_keep,
                   dtype={'job_id': str, 'company_id': str, 'zip_code': str, 'fips': str})


text_cols = ['company_name', 'title', 'description', 'location', 'skills_desc', 'work_type']

for col in text_cols:
    jobs[col] = jobs[col].str.lower().str.strip()

In [72]:
jobs.head()

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips
0,921716,corcoran sawyer smith,marketing coordinator,job descriptiona leading real estate firm in n...,"princeton, nj",2774458.0,20.0,requirements: \n\nwe are seeking a college or ...,full_time,08540,34021
1,1829192,NaN,mental health therapist/counselor,"at aspen therapy and wellness , we are committ...","fort collins, co",NaN,1.0,NaN,full_time,80521,08069
2,10998357,the national exemplar,assitant restaurant manager,the national exemplar is accepting application...,"cincinnati, oh",64896719.0,8.0,we are currently accepting resumes for foh - a...,full_time,45202,39061
3,23221523,"abrams fensterman, llp",senior elder law / trusts and estates associat...,senior associate attorney - elder law / trusts...,"new hyde park, ny",766262.0,16.0,this position requires a baseline understandin...,full_time,11040,36059
4,35982263,NaN,service technician,looking for hvac service tech with experience ...,"burlington, ia",NaN,3.0,NaN,full_time,52601,19057

In [73]:
jobs.tail()

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips
123844,3906267117,lozano smith,title ix/investigations attorney,our walnut creek office is currently seeking a...,"walnut creek, ca",56120.0,1.0,NaN,full_time,94595,06013
123845,3906267126,pinterest,"staff software engineer, ml serving platform",about pinterest:\n\nmillions of people across ...,united states,1124131.0,3.0,NaN,full_time,NaN,NaN
123846,3906267131,eps learning,"account executive, oregon/washington",company overview\n\neps learning is a leading ...,"spokane, wa",90552133.0,3.0,NaN,full_time,99201,53063
123847,3906267195,trelleborg applied technologies,business development manager,the business development manager is a 'hunter'...,"texas, united states",2793699.0,4.0,NaN,full_time,NaN,NaN
123848,3906267224,solugenix,marketing social media specialist,marketing social media specialist - $70k – $75...,"san juan capistrano, ca",43325.0,2.0,NaN,full_time,92675,06059

In [74]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   job_id        123849 non-null  object
 1   company_name  122130 non-null  object
 2   title         123849 non-null  object
 3   description   123842 non-null  object
 4   location      123849 non-null  object
 5   company_id    122132 non-null  object
 6   views         122160 non-null  float64
 7   skills_desc   2439 non-null    object
 8   work_type     123849 non-null  object
 9   zip_code      102977 non-null  object
 10  fips          96434 non-null   object
dtypes: float64(1), object(10)
memory usage: 10.4+ MB

In [75]:
# We notice that some of the rows have country as united states , we dont want this. We have the zip_code and fips code which can help us identify the location of the job,
# We will use the zip_code and fips to get a city and state for each job, for rows where location is united states and no zip_code/fips we will drop those rows. 
# Normalize zip/fips as 5-digit strings (keep leading zeros)


# normalize location safely
jobs['location'] = (
    jobs['location']
    .astype(str)
    .str.strip()
    .str.lower()
)

# define "missing zip" robustly
missing_zip = (
    jobs['zip_code'].isna() |
    (jobs['zip_code'].astype(str).str.strip() == '') |
    (jobs['zip_code'].astype(str).str.lower() == 'nan')
)

mask_drop = (
    jobs['location'].eq('united states') &
    missing_zip &
    jobs['fips'].isna()
)

before = len(jobs)
jobs = jobs[~mask_drop]
after = len(jobs)

print(f"Dropped {before - after} rows")

Dropped 8125 rows

In [76]:
jobs.head(10)

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips
0,921716,corcoran sawyer smith,marketing coordinator,job descriptiona leading real estate firm in n...,"princeton, nj",2774458.0,20.0,requirements: \n\nwe are seeking a college or ...,full_time,08540,34021
1,1829192,NaN,mental health therapist/counselor,"at aspen therapy and wellness , we are committ...","fort collins, co",NaN,1.0,NaN,full_time,80521,08069
2,10998357,the national exemplar,assitant restaurant manager,the national exemplar is accepting application...,"cincinnati, oh",64896719.0,8.0,we are currently accepting resumes for foh - a...,full_time,45202,39061
3,23221523,"abrams fensterman, llp",senior elder law / trusts and estates associat...,senior associate attorney - elder law / trusts...,"new hyde park, ny",766262.0,16.0,this position requires a baseline understandin...,full_time,11040,36059
4,35982263,NaN,service technician,looking for hvac service tech with experience ...,"burlington, ia",NaN,3.0,NaN,full_time,52601,19057
5,91700727,downtown raleigh alliance,economic development and planning intern,job summary:the economic development & plannin...,"raleigh, nc",1481176.0,9.0,NaN,internship,27601,37183
7,112576855,NaN,building engineer,summary: due to the pending retirement of our ...,"san francisco, ca",NaN,2.0,NaN,full_time,94101,06075
8,1218575,children's nebraska,respiratory therapist,"at children’s, the region’s only full-service ...","omaha, ne",721189.0,3.0,• requires the ability to communicate effectiv...,full_time,68102,31055
9,2264355,bay west church,worship leader,it is an exciting time to be a part of our chu...,"palm bay, fl",28631247.0,5.0,"knowledge, skills and abilities: 1. proficient...",part_time,32905,12009
10,9615617,"glastender, inc.",inside customer service associate,glastender inc. is a family-owned manufacturer...,"saginaw, mi",1194336.0,4.0,the production supervisor must possess strong ...,full_time,48601,26145

In [77]:
jobs[jobs['location'] == 'united states'][['location', 'zip_code', 'fips']].head()

Empty DataFrame
Columns: [location, zip_code, fips]
Index: []

In [78]:
zips_raw = pd.read_csv('data/uszips.csv')
zips_raw.columns = zips_raw.columns.str.strip().str.lower()

state_col = next(
    (c for c in ['state', 'state_id', 'state_name'] if c in zips_raw.columns),
    None
)

missing_required = [c for c in ['zip', 'city'] if c not in zips_raw.columns]
if missing_required:
    raise ValueError(f"Missing required columns in uszips.csv: {missing_required}")

if state_col is None:
    zips = zips_raw[['zip', 'city']].copy()
    zips['state'] = pd.NA
else:
    zips = zips_raw[['zip', 'city', state_col]].copy().rename(columns={state_col: 'state'})

zips['zip'] = zips['zip'].astype('string').str.strip().str.zfill(5)
jobs['zip_code'] = jobs['zip_code'].astype('string').str.strip().str.zfill(5)

# make reruns safe in notebook
jobs = jobs.drop(columns=['zip', 'city', 'state'], errors='ignore')

jobs = jobs.merge(
    zips,
    left_on='zip_code',
    right_on='zip',
    how='left'
)

In [79]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115724 entries, 0 to 115723
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   job_id        115724 non-null  object
 1   company_name  114283 non-null  object
 2   title         115724 non-null  object
 3   description   115720 non-null  object
 4   location      115724 non-null  object
 5   company_id    114285 non-null  object
 6   views         114161 non-null  float64
 7   skills_desc   2409 non-null    object
 8   work_type     115724 non-null  object
 9   zip_code      102977 non-null  string
 10  fips          96434 non-null   object
 11  zip           99949 non-null   string
 12  city          99949 non-null   object
 13  state         99949 non-null   object
dtypes: float64(1), object(11), string(2)
memory usage: 12.4+ MB

In [80]:
missing_city_state = jobs['city'].isna() & jobs['state'].isna()

In [81]:
STATE_MAP = {
    'alabama': 'AL', 'alaska': 'AK', 'arizona': 'AZ', 'arkansas': 'AR',
    'california': 'CA', 'colorado': 'CO', 'connecticut': 'CT', 'delaware': 'DE',
    'florida': 'FL', 'georgia': 'GA', 'hawaii': 'HI', 'idaho': 'ID',
    'illinois': 'IL', 'indiana': 'IN', 'iowa': 'IA', 'kansas': 'KS',
    'kentucky': 'KY', 'louisiana': 'LA', 'maine': 'ME', 'maryland': 'MD',
    'massachusetts': 'MA', 'michigan': 'MI', 'minnesota': 'MN',
    'mississippi': 'MS', 'missouri': 'MO', 'montana': 'MT',
    'nebraska': 'NE', 'nevada': 'NV', 'new hampshire': 'NH',
    'new jersey': 'NJ', 'new mexico': 'NM', 'new york': 'NY',
    'north carolina': 'NC', 'north dakota': 'ND', 'ohio': 'OH',
    'oklahoma': 'OK', 'oregon': 'OR', 'pennsylvania': 'PA',
    'rhode island': 'RI', 'south carolina': 'SC', 'south dakota': 'SD',
    'tennessee': 'TN', 'texas': 'TX', 'utah': 'UT', 'vermont': 'VT',
    'virginia': 'VA', 'washington': 'WA', 'west virginia': 'WV',
    'wisconsin': 'WI', 'wyoming': 'WY', 'district of columbia': 'DC'
}

In [82]:
def extract_state_from_location(loc):
    if not isinstance(loc, str):
        return None

    loc_lower = loc.lower()

    for name, abbr in STATE_MAP.items():
        abbr_lower = abbr.lower()

        # check full state name
        if name in loc_lower:
            return abbr

        # check abbreviation as a word boundary (tx, TX, Tx, etc.)
        pattern = rf'\b{abbr_lower}\b'
        if re.search(pattern, loc_lower):
            return abbr

    return None



jobs.loc[missing_city_state, 'state'] = (
    jobs.loc[missing_city_state, 'location']
    .apply(extract_state_from_location)
)

jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115724 entries, 0 to 115723
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   job_id        115724 non-null  object
 1   company_name  114283 non-null  object
 2   title         115724 non-null  object
 3   description   115720 non-null  object
 4   location      115724 non-null  object
 5   company_id    114285 non-null  object
 6   views         114161 non-null  float64
 7   skills_desc   2409 non-null    object
 8   work_type     115724 non-null  object
 9   zip_code      102977 non-null  string
 10  fips          96434 non-null   object
 11  zip           99949 non-null   string
 12  city          99949 non-null   object
 13  state         111748 non-null  object
dtypes: float64(1), object(11), string(2)
memory usage: 12.4+ MB

In [83]:
jobs = jobs.drop(columns=['zip'], errors='ignore')

In [84]:
jobs.head()

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips,city,state
0,921716,corcoran sawyer smith,marketing coordinator,job descriptiona leading real estate firm in n...,"princeton, nj",2774458.0,20.0,requirements: \n\nwe are seeking a college or ...,full_time,08540,34021,Princeton,NJ
1,1829192,NaN,mental health therapist/counselor,"at aspen therapy and wellness , we are committ...","fort collins, co",NaN,1.0,NaN,full_time,80521,08069,Fort Collins,CO
2,10998357,the national exemplar,assitant restaurant manager,the national exemplar is accepting application...,"cincinnati, oh",64896719.0,8.0,we are currently accepting resumes for foh - a...,full_time,45202,39061,Cincinnati,OH
3,23221523,"abrams fensterman, llp",senior elder law / trusts and estates associat...,senior associate attorney - elder law / trusts...,"new hyde park, ny",766262.0,16.0,this position requires a baseline understandin...,full_time,11040,36059,New Hyde Park,NY
4,35982263,NaN,service technician,looking for hvac service tech with experience ...,"burlington, ia",NaN,3.0,NaN,full_time,52601,19057,Burlington,IA

In [85]:
# We drop the rows where state is NaN even after our best efforts to extract it from the location string, we will not be able to use those rows in our analysis and 
# they are a small percentage of the total data so we can afford to drop them.

jobs = jobs.dropna(subset=['state'])
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 111748 entries, 0 to 115723
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   job_id        111748 non-null  object
 1   company_name  110422 non-null  object
 2   title         111748 non-null  object
 3   description   111745 non-null  object
 4   location      111748 non-null  object
 5   company_id    110424 non-null  object
 6   views         110298 non-null  float64
 7   skills_desc   2310 non-null    object
 8   work_type     111748 non-null  object
 9   zip_code      102977 non-null  string
 10  fips          96434 non-null   object
 11  city          99949 non-null   object
 12  state         111748 non-null  object
dtypes: float64(1), object(11), string(1)
memory usage: 11.9+ MB

In [108]:
#  Use only 50% of cleaned real job dataset

jobs_sample = jobs.sample(n=int(0.5 * len(jobs)), random_state=42).reset_index(drop=True)

# Lets also save the job_sample to a csv file. we will use it for synthetic data generation and testing our model later on.
jobs_sample.to_csv('data/jobs_sample.csv', index=False)

print("Original cleaned jobs shape:", jobs.shape)
print("sampled jobs shape:", jobs_sample.shape)

Original cleaned jobs shape: (111748, 13)
sampled jobs shape: (55874, 13)

In [109]:
jobs_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55874 entries, 0 to 55873
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_id        55874 non-null  object
 1   company_name  55211 non-null  object
 2   title         55874 non-null  object
 3   description   55873 non-null  object
 4   location      55874 non-null  object
 5   company_id    55211 non-null  object
 6   views         55145 non-null  float64
 7   skills_desc   1128 non-null   object
 8   work_type     55874 non-null  object
 9   zip_code      51474 non-null  string
 10  fips          48213 non-null  object
 11  city          49949 non-null  object
 12  state         55874 non-null  object
dtypes: float64(1), object(11), string(1)
memory usage: 5.5+ MB

In [110]:
jobs_sample.head()

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips,city,state
0,3903466305,cabela's,firearms outfitter - part time,position summary:\n\nthe sales outfitter - fir...,"lubbock, tx",12890.0,4.0,NaN,part_time,79401,48303,Lubbock,TX
1,3887485157,mission staffing,administrative assistant,"our client, a global law firm in washington, d...",washington dc-baltimore area,132319.0,32.0,NaN,full_time,<NA>,NaN,NaN,WA
2,3895598418,harbor freight tools,retail stocking supervisor,a supervisor (full-time) is a valued member of...,"chino hills, ca",28923.0,5.0,NaN,full_time,91709,06071,Chino Hills,CA
3,3906097453,bmo u.s.,"director, corporate development","reporting to vp/head of corporate development,...","chicago, il",164126.0,4.0,NaN,full_time,60601,17031,Chicago,IL
4,3903473957,university of south florida,general maintenance technician iii,department number/name: 0-0255-001 / maintenan...,"tampa, fl",166671.0,4.0,NaN,full_time,33602,12057,Tampa,FL

# Loading the student dataset and cleaning it

In [89]:
students_data = pd.read_csv("data\student_data.csv")
# lets convert all the columns to lowercase to avoid any issues with case sensitivity when we do our analysis later on.
str_cols = students_data.select_dtypes(include=["object", "string"]).columns
students_data[str_cols] = students_data[str_cols].apply(lambda col: col.str.lower())
students_data["Skill"] = (
    students_data["Skill"]
    .str.strip("[]")
    .str.replace('"', '')
)
students_data.head()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\maina\AppData\Local\Temp\ipykernel_26768\4265789378.py:1: SyntaxWarning: invalid escape sequence '\s'
  students_data = pd.read_csv("data\student_data.csv")

,Student ID,Academic Major,GPA,Skill,Location Interest,University,School Year,Area of Experience,Number of Experience (yrs),Degree
0,stu000001,marketing,3.53,"client communication, market research, social ...",remote / flexible,boston university,sophomore,customer success,1.2,bachelor's
1,stu000002,finance,3.83,"collaboration, presentation skills, compliance...","seattle, wa",university of michigan,junior,risk management,1.6,bachelor's
2,stu000003,electrical engineering,3.70,"documentation, communication, verilog, problem...","washington, dc",university of pennsylvania,sophomore,electrical systems,0.9,bachelor's
3,stu000004,civil engineering,2.89,"project planning, civil 3d, attention to detai...","washington, dc",cornell university,senior,environmental engineering,3.2,bachelor's
4,stu000005,english,3.74,"editing, storytelling, content creation, prese...","san francisco bay area, ca",stanford university,freshman,communications,0.4,bachelor's

In [90]:
students_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student ID                  25000 non-null  object
 1   Academic Major              25000 non-null  object
 2   GPA                         25000 non-null  float64
 3   Skill                       25000 non-null  object
 4   Location Interest           25000 non-null  object
 5   University                  25000 non-null  object
 6   School Year                 25000 non-null  object
 7   Area of Experience          25000 non-null  object
 8   Number of Experience (yrs)  25000 non-null  float64
 9   Degree                      25000 non-null  object
dtypes: float64(2), object(8)
memory usage: 1.9+ MB

In [ ]:
#  Keep only 5000 student rows
students_sample = students_data.sample(n=5000, random_state=42).reset_index(drop=True)

print("Original students_data shape:", students_data.shape)
print("Student sample shape:", students_sample.shape)

Original students_data shape: (25000, 10)
Student sample shape: (5000, 10)

In [92]:
students_sample.head()

,Student ID,Academic Major,GPA,Skill,Location Interest,University,School Year,Area of Experience,Number of Experience (yrs),Degree
0,stu006869,computer science,3.20,"git, java, organization","seattle, wa",university of washington,sophomore,machine learning,0.8,bachelor's
1,stu024017,biology,3.57,"pcr, collaboration, presentation skills, spss,...","san diego, ca","university of california, san diego",2nd year master's,laboratory science,3.4,master's
2,stu009669,data science,3.57,"leadership, scikit-learn, problem solving, ini...","new york, ny",rutgers university,junior,machine learning,1.2,bachelor's
3,stu013641,economics,3.11,"policy analysis, adaptability, stata, r, prese...",remote / flexible,duke university,junior,finance,2.0,bachelor's
4,stu014019,business administration,3.23,"project management, sql, excel, presentation s...",remote / flexible,university of chicago,senior,finance,3.4,bachelor's

# Text Vectorization

In [111]:
def build_job_text(jobs_sample):
    jobs_sample = jobs_sample.copy()
    jobs_sample["description"] = jobs_sample["description"].fillna("")
    jobs_sample["job_text"] = (jobs_sample["title"] + " " + jobs_sample["description"]).str.strip()
    return jobs_sample

In [112]:
jobs_text = build_job_text(jobs_sample)
jobs_text.head()

,job_id,company_name,title,description,location,company_id,views,skills_desc,work_type,zip_code,fips,city,state,job_text
0,3903466305,cabela's,firearms outfitter - part time,position summary:\n\nthe sales outfitter - fir...,"lubbock, tx",12890.0,4.0,NaN,part_time,79401,48303,Lubbock,TX,firearms outfitter - part time position summar...
1,3887485157,mission staffing,administrative assistant,"our client, a global law firm in washington, d...",washington dc-baltimore area,132319.0,32.0,NaN,full_time,<NA>,NaN,NaN,WA,"administrative assistant our client, a global ..."
2,3895598418,harbor freight tools,retail stocking supervisor,a supervisor (full-time) is a valued member of...,"chino hills, ca",28923.0,5.0,NaN,full_time,91709,06071,Chino Hills,CA,retail stocking supervisor a supervisor (full-...
3,3906097453,bmo u.s.,"director, corporate development","reporting to vp/head of corporate development,...","chicago, il",164126.0,4.0,NaN,full_time,60601,17031,Chicago,IL,"director, corporate development reporting to v..."
4,3903473957,university of south florida,general maintenance technician iii,department number/name: 0-0255-001 / maintenan...,"tampa, fl",166671.0,4.0,NaN,full_time,33602,12057,Tampa,FL,general maintenance technician iii department ...

In [113]:
nlp = spacy.load("en_core_web_sm")

def normalize_title_spacy(title):
    doc = nlp(title.lower())
    
    # Keep nouns and proper nouns (core job meaning)
    tokens = [token.text for token in doc if token.pos_ in ["NOUN", "PROPN"]]
    
    return " ".join(tokens)

In [114]:
jobs_text["normalized_title"] = jobs_text["title"].apply(normalize_title_spacy)
jobs_text[["title", "normalized_title"]].head()

                                title              normalized_title
0      firearms outfitter - part time  firearms outfitter part time
1            administrative assistant                     assistant
2          retail stocking supervisor           stocking supervisor
3     director, corporate development          director development
4  general maintenance technician iii    maintenance technician iii

# Bert Model Training on real job data

In [115]:
from sentence_transformers import SentenceTransformer

def vectorize_jobs_bert(jobs_text):
    model = SentenceTransformer('all-MiniLM-L6-v2')

    job_vectors = model.encode(
        jobs_text["job_text"].tolist(),
        show_progress_bar=True
    )

    return model, job_vectors

In [116]:
model, job_vectors = vectorize_jobs_bert(jobs_text)

print("Job text shape:", jobs_text.shape)
print("Job vectors shape:", job_vectors.shape)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3110.02it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 1747/1747 [37:42<00:00,  1.29s/it]

Job text shape: (55874, 15)
Job vectors shape: (55874, 384)

In [117]:
def build_student_text(students):
    students = students.copy()
    students["student_text"] = (
        students["Academic Major"].fillna("") + " " +
        students["Skill"].fillna("") + " " +
        students["Area of Experience"].fillna("") + " " +
        students["School Year"].fillna("") + " "+
        students["Degree"].fillna("")
    ).str.strip()
    return students

In [118]:
student_text = build_student_text(students_sample)
student_text.head()

,Student ID,Academic Major,GPA,Skill,Location Interest,University,School Year,Area of Experience,Number of Experience (yrs),Degree,student_text
0,stu006869,computer science,3.20,"git, java, organization","seattle, wa",university of washington,sophomore,machine learning,0.8,bachelor's,"computer science git, java, organization machi..."
1,stu024017,biology,3.57,"pcr, collaboration, presentation skills, spss,...","san diego, ca","university of california, san diego",2nd year master's,laboratory science,3.4,master's,"biology pcr, collaboration, presentation skill..."
2,stu009669,data science,3.57,"leadership, scikit-learn, problem solving, ini...","new york, ny",rutgers university,junior,machine learning,1.2,bachelor's,"data science leadership, scikit-learn, problem..."
3,stu013641,economics,3.11,"policy analysis, adaptability, stata, r, prese...",remote / flexible,duke university,junior,finance,2.0,bachelor's,"economics policy analysis, adaptability, stata..."
4,stu014019,business administration,3.23,"project management, sql, excel, presentation s...",remote / flexible,university of chicago,senior,finance,3.4,bachelor's,"business administration project management, sq..."

In [119]:
student_vectors = model.encode(
    student_text["student_text"].tolist(),
    show_progress_bar=True
)

print("Student text shape:", student_text.shape)
print("Student vectors shape:", student_vectors.shape)

Batches: 100%|██████████| 157/157 [00:27<00:00,  5.66it/s]

Student text shape: (5000, 11)
Student vectors shape: (5000, 384)

In [120]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(student_vectors, job_vectors)

print("Similarity matrix shape:", similarity_matrix.shape)

top_k = 5
top_matches = np.argsort(-similarity_matrix, axis=1)[:, :top_k]

results = []

for student_idx, job_idxs in enumerate(top_matches):
    for rank, job_idx in enumerate(job_idxs, start=1):
        results.append({
            "student_index": student_idx,
            #"student_text": student_text.iloc[student_idx]["student_text"],
            "job_index": job_idx,
            "job_id": jobs_text.iloc[job_idx]["job_id"],
            #"job_title": jobs_text.iloc[job_idx]["title"],
            "job_title_normalized": jobs_text.iloc[job_idx]["normalized_title"],
            #"job_text": jobs_text.iloc[job_idx]["job_text"],
            "similarity_score": similarity_matrix[student_idx, job_idx],
            "rank": rank
        })

matches_df = pd.DataFrame(results)
matches_df.head(10)

Similarity matrix shape: (5000, 55874)

,student_index,job_index,job_id,job_title_normalized,similarity_score,rank
0,0,23036,3902750199,stack developer,0.566738,1
1,0,44405,3901945351,lead instructor computer science summer camp,0.565228,2
2,0,52444,3886880291,java specialist,0.563917,3
3,0,31648,3887473170,java engineer,0.563591,4
4,0,17654,3902804122,programmer java)-experience analysis tools,0.562465,5
5,1,22136,3901676070,applications lab associate,0.614301,1
6,1,39190,3887702242,scientist cell culture elisa potency assays pcr,0.599373,2
7,1,40516,3887467922,chemistry scientist,0.570340,3
8,1,11450,3901952935,research technician b,0.558262,4
9,1,16795,3904958825,laboratory technician,0.558121,5

In [122]:
student_id_to_check = 20

top_jobs = matches_df[matches_df["student_index"] == student_id_to_check].copy()
top_jobs

,student_index,job_index,job_id,job_title_normalized,similarity_score,rank
100,20,8371,3891257314,data scientist,0.643499,1
101,20,182,3886830826,data scientist,0.642203,2
102,20,12439,3904361248,data scientist,0.607011,3
103,20,30918,3899524261,data scientist,0.599163,4
104,20,36037,3903869892,data science visualization engineer,0.591028,5

In [123]:
title_scores = (
    top_jobs.groupby("job_title_normalized", as_index=False)
    .agg(
        avg_similarity=("similarity_score", "mean"),
        retrieved_posting_count=("job_id", "count")
    )
    .rename(columns={"job_title_normalized": "title"})
)

title_scores["combined_score"] = (
    title_scores["avg_similarity"] *
    np.log1p(title_scores["retrieved_posting_count"])
)

title_scores = title_scores.sort_values("combined_score", ascending=False)

print("\nMatched titles:")
print(title_scores.head(10))

Matched titles:
                                 title  avg_similarity  \
1                       data scientist        0.622969
0  data science visualization engineer        0.591028

   retrieved_posting_count  combined_score
1                        4         1.00263
0                        1         0.40967

In [124]:
def normalize_state_value(x):
    import pandas as pd

    if pd.isna(x):
        return ""

    x = str(x).strip().lower()
    
    if len(x) == 2:
        return x.upper()

    return STATE_MAP.get(x, x.upper())

# Location interest matching

In [125]:
top_titles_df = title_scores.head(5).copy()

student_row = students_sample.iloc[student_id_to_check]
preferred_location_raw = student_row["Location Interest"]
preferred_state = normalize_state_value(preferred_location_raw)

print(f"Student: {student_row['Academic Major']} student")
print(f"Preferred location: {preferred_location_raw}\n")
print("Top Career Matches:\n")

for i, (_, row) in enumerate(top_titles_df.iterrows(), start=1):
    title = row["title"]
    fit_score = row["avg_similarity"]

    all_states = (
        jobs_text[jobs_text["normalized_title"] == title]
        .groupby("state", as_index=False)
        .size()
        .rename(columns={"size": "demand_count"})
        .sort_values("demand_count", ascending=False)
    )

    top_states = all_states.head(5)

    state_list = [
        f"{r['state']} ({r['demand_count']})"
        for _, r in top_states.iterrows()
    ]

    print(f"{i}. {title.title()}")
    print(f"   Fit Score: {fit_score:.4f}")
    print(f"   Top Demand Locations: {', '.join(state_list)}")
    print()

Student: data science student
Preferred location: philadelphia, pa

Top Career Matches:

1. Data Scientist
   Fit Score: 0.6230
   Top Demand Locations: TX (8), CA (7), VA (6), FL (4), AR (3)

2. Data Science Visualization Engineer
   Fit Score: 0.5910
   Top Demand Locations: CA (1)